
{{- if eq .Values.global.prometheus.ip  "" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: middleware-prometheus
  namespace: {{ .Release.Namespace }} 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: middleware-prometheus
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  resources:
    - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: middleware-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: middleware-prometheus
subjects:
- kind: ServiceAccount
  name: middleware-prometheus
  namespace: {{ .Release.Namespace }} 
{{- end }}