# Default values for middleware_sqlserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  elastic:
    ip: ""

  volumeclaims:
    enabled: true
    storageSize: 4Gi
    storageClassName: 

replicaCount: 1

image:
  repository: registry.cn-hangzhou.aliyuncs.com/masastack/elasticsearch
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "7.6.2.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  # type: NodePort
  type: ClusterIP
  port: 9200
  # nodePort: "30200"

resources:
  limits:
    cpu: "2000m"
    memory: "4Gi"
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
