{{- if eq .Values.global.elastic.ip  "" -}}
apiVersion: v1
kind: Service
metadata:
  name: middleware-elastic
  labels:
    {{- include "middleware-elastic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: middleware-elastic
{{- if eq .Values.service.type  "NodePort" }}
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
{{- end }}
  selector:
    app: middleware-elastic
{{- end }}