version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The MASA_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     MASA_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file

services:

  middleware-elastic:
    ports:
      - "5200:9200"
      - "5300:9300"

  middleware-redis:
    ports:
      - "5379:6379"

  middleware-sqlserver:
    environment:
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=p@ssw0rd
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - sqldata:/var/opt/mssql


  alert-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5103:80"

  alert-service-dapr:
    command: ["./daprd",
      "-app-id", "alert-service",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/masa-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

 
  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

volumes:
  sqldata:
    external: false  

