apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}
  labels:
    app: {{ .Values.server.name }}
    {{- include "tsc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.type }}
  ports:
    - port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.server.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.name }}
  labels:
    app: {{ .Values.ui.name }}
    {{- include "tsc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.type }}
  ports:
    - port: {{ .Values.ui.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.ui.name }}