apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "masastack.labels" . | nindent 4}}
data:
  SUFFIX_IDENTITY: ""
  ENVIRONMENT: Production
  PROMETHEUS: http://middleware-prometheus:9090
  OTLP_URL: http://middleware-otel:4317
  NAMESPACE: {{ .Release.Namespace }}
  VERSION: "1.0-Preview1"
  CLUSTER: "Default"
  DCC_SECRET: "masastack.com"
  ADMIN_PWD: "admin123"
  DOMAIN_NAME: {{ .Values.global.domain }}
{{- if eq .Values.global.sqlserver.ip "" }}
  CONNECTIONSTRING: |-
    {"Server": "middleware-sqlserver", "Port": 1433,"Database":"","UserId": "sa","Password":"{{ .Values.global.sqlserver.password }}"}
{{- else }}
  CONNECTIONSTRING: |-
    {"Server": "{{ .Values.global.sqlserver.ip }}", "Port": {{ .Values.global.sqlserver.port }},"Database":"","UserId": "{{ .Values.global.sqlserver.id }}","Password":"{{ .Values.global.sqlserver.password }}"}
{{- end }}
{{- if eq  .Values.global.redis.ip "" }}
  REDIS: |-
    {"RedisHost": "middleware-redis", "RedisPort": 6379, "RedisDb": 0,"RedisPassword": "{{ .Values.global.redis.password }}"}
{{- else }}
  REDIS: |-
    {"RedisHost": "{{ .Values.global.redis.ip }}", "RedisPort": {{ .Values.global.redis.port }}, "RedisDb": {{.Values.global.redis.db }},"RedisPassword": "{{ .Values.global.redis.password }}"}
{{- end }}
{{- if eq .Values.global.elastic.ip "" }}
  ELASTIC: |- 
    {"Nodes": ["http://middleware-elastic:9200"],"Index": "auth_user"}
{{- else }}
  ELASTIC: |- 
    {"Nodes": ["http://{{ .Values.global.elastic.ip }}:{{ .Values.global.elastic.port }}"],"Index": "masastack"}
{{- end }}
  TLS_NAME:  {{ .Values.global.ingress.secretName }}
  {{- if eq .Values.global.demo true }}
  IS_DEMO: "true"
  {{- else }}
  IS_DEMO: "false"
  {{- end }}
  MASA_SERVER: |-
    {"pm":{"server":"{{ .Values.pm.server.name }}"},"dcc":{"server":"{{ .Values.dcc.server.name }}"},"auth":{"server":"{{ .Values.auth.server.name }}"},"mc":{"server":"{{ .Values.mc.server.name }}"},"scheduler":{"server":"{{ .Values.scheduler.server.name }}","worker":"{{ .Values.scheduler.worker.name }}"},"tsc":{"server":"{{ .Values.tsc.server.name }}"},"alert":{"server":"{{ .Values.alert.server.name }}"}}
  MASA_UI: |-
    {"pm":{"ui":"{{ .Values.pm.ui.name }}{{- if .Values.global.demo -}}-demo{{- end -}}"},"dcc":{"ui":"{{ .Values.dcc.ui.name }}{{- if .Values.global.demo -}}-demo{{- end -}}"},"auth":{"ui":"{{ .Values.auth.ui.name }}{{- if .Values.global.demo -}}-demo{{- end -}}","sso":"{{ .Values.auth.sso.name }}{{- if .Values.global.demo -}}-demo{{- end -}}"},"mc":{"ui":"{{ .Values.mc.ui.name }}{{- if .Values.global.demo -}}-demo{{- end -}}"},"scheduler":{"ui":"{{ .Values.scheduler.ui.name }}{{- if .Values.global.demo -}}-demo{{- end -}}"},"tsc":{"ui":"{{ .Values.tsc.ui.name }}{{- if .Values.global.demo -}}-demo{{- end -}}"},"alert":{"ui":"{{ .Values.alert.ui.name }}{{- if .Values.global.demo -}}-demo{{- end -}}"}}
